출처:

https://github.com/zerosum99/tensorflow_ipynb/blob/master/tensorflow%20300_%ED%85%90%EC%84%9C%ED%94%8C%EB%A1%9C%EC%9A%B0%20%EC%A3%BC%EC%9A%94%20%ED%95%A8%EC%88%98%20%EC%B2%98%EB%A6%AC%2020170331.ipynb


In [9]:
import tensorflow as tf
import numpy as np

### Arithmetic Operators
tf.add(x, y, name=None)

tf.sub(x, y, name=None)

tf.mul(x, y, name=None),     tf.scalar_mul(scalar, x)

tf.div(x, y, name=None),         tf.mod(x, y, name=None)

tf.truediv(x, y, name=None),     tf.floordiv(x, y, name=None)

tf.cross(a, b, name=None)

In [4]:
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

add = tf.add(a,b)
sub = tf.subtract(a,b) # 버전업데이트 이후 메소드명 바뀜
mul = tf.multiply(a,b) # 버전업데이트 이후 메소드명 바뀜
sca = tf.scalar_mul(3,a)

div = tf.div(b,a) # 정수 나누기
mod = tf.mod(b,a)

trdiv = tf.truediv(b,a)
fldiv = tf.floordiv(b,a)
cro   = tf.cross(a,b)

with tf.Session() as sess :
    print(add.eval())
    print(sub.eval())
    print(mul.eval())
    print(sca.eval())
    print(div.eval())
    print(mod.eval())
    print(trdiv.eval())
    print(fldiv.eval())
    
    # 벡터곱 처리 [a1b2-a2b1,a3b1-a1b3, a2b3-a3b2 ]
    # [5, 12, 12 ] [8,6,15]
    print(cro.eval())

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[3 6 9]
[4 2 2]
[0 1 0]
[4.  2.5 2. ]
[4 2 2]
[-3  6 -3]


### 복소수
tf.complex

tf.conj

tf.imag

tf.real

In [25]:
real = tf.constant([2.25, 3.25], name="real")
imag  = tf.constant([4.75, 5.75], name="imag")
com = tf.complex(real, imag) 

with tf.Session() as sess :
    print(sess.run(com))
    print(sess.run(tf.conj(com)))
    print(sess.run(tf.real(com)))
    print(sess.run(tf.imag(com)))

[2.25+4.75j 3.25+5.75j]
[2.25-4.75j 3.25-5.75j]
[2.25 3.25]
[4.75 5.75]


### Basic Math Functions
tf.reciprocal

tf.square

tf.round

tf.sqrt,     tf.rsqrt

tf.pow,     tf.exp,     tf.expm1

tf.log,tf.log1p

tf.ceil,     tf.floor

tf.maximum, tf.minimum

tf.cos, tf.sin, tf.tan

tf.lbeta

tf.acos, tf.asin, tf.atan

tf.lgamma

tf.digamma

tf.erf, tf.erfc

tf.squared_difference

tf.igamma

tf.igammac

tf.zeta

tf.polygamma

tf.betainc

tf.rint


In [5]:
# 리스트 내의 텐서들 값을 더하기 : tf.add_n
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])

# 텐서를 가진 리스트 처리
l =[]
l.append(a)
l.append(b)
addn = tf.add_n(l)

with tf.Session() as sess :
    print(addn.eval())

[5 7 9]


In [6]:
# 텐서 내의 부호 처리 : sign, negative, abs
a = tf.constant([-1,-2,-3])
b = tf.constant([4,5,6])
c = tf.constant([0,0,0])

ab = tf.abs(a)
neg = tf.negative(a)
# 음수이면 -1
sig = tf.sign(a)
# 양수이면 1
sig1 = tf.sign(b)

# 0이면 0
sig0 = tf.sign(c)

with tf.Session() as sess :
    print(ab.eval())
    print(neg.eval())
    print(sig.eval())
    print(sig1.eval())
    print(sig0.eval())

[1 2 3]
[1 2 3]
[-1 -1 -1]
[1 1 1]
[0 0 0]


### Matrix Math Functions

tf.matrix_diag

tf.matrix_diag_part

tf.matrix_band_part

tf.matrix_set_diag

tf.matrix_transpose

tf.norm

tf.cholesky

tf.cholesky_solve

tf.matrix_solve

tf.matrix_triangular_solve

tf.matrix_solve_ls

tf.qr

tf.self_adjoint_eig

tf.self_adjoint_eigvals

tf.svd

In [10]:
# 행렬식과 역행렬 구하기
# 행렬식을 먼저 구해서 0이 아니어야 역행렬을 구할 수 있다

x = tf.Variable([[1, 2], [3,4]],dtype=tf.float32)

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)

    print(sess.run(x))
    print(sess.run(tf.shape(x)))
    print(sess.run(tf.matrix_determinant(x)))

    xi = sess.run(tf.matrix_inverse(x))

    print(xi)
    print(np.linalg.inv([[1, 2], [3,4]]))

    print(sess.run(tf.matmul(xi,x)))

[[1. 2.]
 [3. 4.]]
[2 2]
-2.0
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[ 1.0000002e+00  0.0000000e+00]
 [-1.1920929e-07  1.0000000e+00]]


In [8]:
# 단위 행렬 만들기
#eye(num_rows, num_columns=None, batch_shape=None, dtype=tf.float32, name=None)

sess = tf.Session()
print(sess.run(tf.eye(2)))
print(sess.run(tf.eye(3,3)))
sess.close()

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# 전치행렬 및 행렬곱(matmul)
x = tf.constant([[1, 2, 3], [4, 5, 6]])

ax = tf.matmul(x,tf.transpose(x))

sess = tf.Session()
print(sess.run(x))
print(sess.run(tf.transpose(x)))

print(sess.run(ax))

sess.close()

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[[14 32]
 [32 77]]


In [12]:
# 대각행렬의 합
x = tf.constant([[1, 2, 3], [4, 5, 6],[7,8,9]])

sess = tf.Session()
print(sess.run(x))
print(sess.run(tf.trace(x)))

sess.close()

[[1 2 3]
 [4 5 6]
 [7 8 9]]
15


In [13]:
# 대각행렬 처리 : diag, 대각행렬 값만 추출 diag_part
ma = np.arange(4)
print(ma)

# 특정 벡터의 값을 대각행렬에 세팅
diag = tf.diag(ma)

with tf.Session() as sess :
    print(diag.eval())
    print(tf.diag_part(diag.eval()).eval())

[0 1 2 3]
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
[0 1 2 3]


### Reduction
tf.reduce_logsumexp

tf.einsum

In [14]:
# 내부 원소에 대한 합과 곱 : tf.reduce_sum, tf.reduce_prod

a = tf.constant([-1,-2,-3])
re_s = tf.reduce_sum(a)
re_p = tf.reduce_prod(a)

with tf.Session() as sess :
    print(re_s.eval())
    print(re_p.eval())

-6
-6


In [15]:
# 텐서로 구성된 리스트 내의 원소들을 더하기
a = tf.constant([-1,-2,-3])
re_s = tf.accumulate_n([a,a,a])


with tf.Session() as sess :
    print(re_s.eval())

[-3 -6 -9]


In [16]:
# 원소들에 대한 평균(mean), 원소들이 zero가 아닌 경우
a = tf.constant([0,0,0,1,2,3])
re_s = tf.count_nonzero(a)
re_p = tf.reduce_mean(a)

with tf.Session() as sess :
    print(re_s.eval())
    print(re_p.eval())

3
1


In [17]:
# 내부 원소들에 대한 min/max
a = tf.constant([-1,-2,-3])
re_s = tf.reduce_min(a)
re_p = tf.reduce_max(a)

with tf.Session() as sess :
    print(re_s.eval())
    print(re_p.eval())

-3
-1


In [19]:
# 내부 원소들에 대한 True/False check
a = tf.constant([True,False,True])
re_s = tf.reduce_all(a)
re_p = tf.reduce_any(a)

with tf.Session() as sess :
    print(re_s.eval())
    print(re_p.eval())

False
True


### Scan
누적하는 값을 생성

In [20]:
a = tf.constant([-1,-2,-3])
re_s = tf.cumsum(a)
re_p = tf.cumprod(a)

with tf.Session() as sess :
    print(re_s.eval())
    print(re_p.eval())

[-1 -3 -6]
[-1  2 -6]


### Segment

tf.segment_prod

tf.segment_min

tf.segment_max

tf.segment_mean

tf.unsorted_segment_sum

tf.sparse_segment_sum

tf.sparse_segment_mean

tf.sparse_segment_sqrt_n

### segment id 나누기
segment_ids = [0,1,1]은 첫번째 와 나머지 합으로 분리

segment_ids = [0,0,0]은 하나로 합치기

segment_ids = [0,0,1]은 첫번째와 두번째를 합하고  나머지를 분리

In [22]:
c = tf.constant([[1,2,3,4], [-1,-2,-3,-4], [5,6,7,8]])
seg_s = tf.segment_sum(c, tf.constant([0, 1, 1]))
seg_s0 = tf.segment_sum(c, tf.constant([0,0,0]))
seg_s1 = tf.segment_sum(c, tf.constant([0,0,1]))

with tf.Session() as sess :
    print(seg_s.eval())
    print(seg_s0.eval())
    print(seg_s1.eval())

[[1 2 3 4]
 [4 4 4 4]]
[[5 6 7 8]]
[[0 0 0 0]
 [5 6 7 8]]


### Sequence Comparison and Indexing
tf.setdiff1d

tf.where

tf.edit_distance

tf.invert_permutation

In [23]:
# 최소값과 최대값 index 알아보기
c = tf.constant([[1,2,3,4], [-1,-2,-3,-4], [5,6,7,8]])

# 열단위로 최소값 
seg_min = tf.argmin(c,0) 
# 행단위로 최대값
seg_max = tf.argmax(c,1) 

with tf.Session() as sess :
    print(seg_min.eval())
    print(seg_max.eval())

[1 1 1 1]
[3 0 3]


In [24]:
# 동일한 원소들을 확인하기

c = tf.constant([1,1,1,3,3,4,5,7])

seg_u = tf.unique(c) 


with tf.Session() as sess :
    print(sess.run(seg_u))

Unique(y=array([1, 3, 4, 5, 7], dtype=int32), idx=array([0, 0, 0, 1, 1, 2, 3, 4], dtype=int32))
